### ISSUE TITLE
Code does not work with WSDL version 2021-11-01

### ISSUE THREAD

**Issue by poggs** [openraildata/openldbws-example-python#2]
After upgrading the code to use WSDL version 2021-11-01, Zeep reports the following error:

```zeep.exceptions.XMLParseError: Unexpected element '{http://thalesgroup.com/RTTI/2021-11-01/ldb/types}coach'```

This element is defined - 'coaches' in ```https://lite.realtime.nationalrail.co.uk/OpenLDBWS/rtti_2021-11-01_ldb_types.xsd``` is an ```ArrayOfCoaches``` from ```https://lite.realtime.nationalrail.co.uk/OpenLDBWS/rtti_2017-10-01_ldb_types.xsd```, which is a sequence of CoachData from the same XSD.  However, Zeep seems not to be parsing this correctly.

**Comment by poggs** [comment]
This is not a problem using Apache CXF in https://github.com/openraildata/openldbws-example-java, so is likely a bug with Zeep as @EvelynSubarrow suggests

**Comment by zhibek** [comment]
I faced the same problem.

Investigating what Zeep had a problem with I found the exception was raised from 
`zeep.xsd.types.complex`:
```
            # Check if all children are consumed (parsed)
            if elements:
                if schema.settings.strict:
                    raise XMLParseError("Unexpected element %r" % elements[0].tag)
                else:
                    init_kwargs["_raw_elements"] = elements
```
^^ https://github.com/mvantellingen/python-zeep/blob/4.1.0/src/zeep/xsd/types/complex.py#L214-L219

The logic preventing all children being consumed is in `zeep.xsd.elements.element`:
```
            # If both elements have a namespace and they don't match then skip
            element_tag = etree.QName(xmlelements[0].tag)
            if (
                element_tag.namespace
                and self.qname.namespace
                and element_tag.namespace != self.qname.namespace
                and schema.settings.strict
            ):
                break
```
^^ https://github.com/mvantellingen/python-zeep/blob/4.1.0/src/zeep/xsd/elements/element.py#L163-L171

Debugging showed that when `coach` elements are being processed, the local variables set are:
```
element_tag.namespace = "http://thalesgroup.com/RTTI/2021-11-01/ldb/types"
self.qname.namespace = "http://thalesgroup.com/RTTI/2017-10-01/ldb/types"
```

Due to the namespace mismatch, when `schema.settings.strict` is set, processing of `coach` elements are skipped.

I don't have a good WSDL parser alternative to Zeep, so I haven't been able to determine if this namespace mismatch is valid or a mis-reading further up the Zeep stack. However, setting `strict = False` in Zeep settings allows more forgiving validation and allows processing to proceed. PR #3 implements this setting.
